---
- name: Download nerdctl
  ansible.builtin.get_url:
    checksum: sha256:https://github.com/containerd/nerdctl/releases/download/v1.0.0/SHA256SUMS
    url: "{{ nerdctl_download_url }}"
    dest: "{{ nerdctl_tarball_path }}"

- name: Install nerdctl FULL to /usr/local/
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ nerdctl_tarball_path }}"
    dest: /usr/local/
    creates: /usr/local/bin/nerdctl

- name: Install sysctls for rootless
  ansible.builtin.copy:
    src: 99-rootless.conf.j2
    dest: /etc/sysctl.d/99-rootless.conf
    owner: root
    group: root
    mode: '0644'

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ ubuntu_packages }}"

- name: Generate /etc/subuid
  ansible.builtin.command:
    cmd: |
      for uid in {1000..65536}; do
        uidx=$[ $uid * 65536 ]
        echo "${uid}:${uidx}:65536" >> /etc/subuid
      done
    creates: /etc/subuid

- name: Generate /etc/subgid
  ansible.builtin.command:
    cmd: |
      for gid in {1000..65536}; do
        gidx=$[ $gid * 65536 ]
        echo "${gid}:${gidx}:65536" >> /etc/subgid
      done
    creates: /etc/subgid

- name: Run systemd's loginctl to enable lingering services for user 
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ lingering_user }}"
